### ISSUE TITLE
question about perspective training

### ISSUE THREAD

**Issue by wanghxcis** [zouchuhang/LayoutNet#37]
I want to train the perspective model from scratch, but I can' t find info_edg_stack_tr_lsun_640_d6_sig20_trname.t7, can you tell me where I can get this dataset.

**Comment by zouchuhang** [comment]
@wanghxcis They should be included in this data file mentioned in Readme: https://drive.google.com/file/d/1BSYquS7LietkRiyZMxBlqtY8uZSIsUUg/view

**Comment by wanghxcis** [comment]
Hi, thanks for your answer, and unzip LSUN_data.zip, there are only three folders "lsun_tr  lsun_ts  lsun_val", and I can't 
 find info_edg_stack_tr_lsun_640_d6_sig20_trname.t7, could you give me some hint about this? Thanks very much @zouchuhang

**Comment by zouchuhang** [comment]
@wanghxcis Thank you for your detailed check. It seems that there's no "info_edg_stack_tr_lsun_640_d6_sig20_trname.t7" in the current data file. I do not have a local copy of it so I'm sorry that I cannot recover this file. However, since the content in "info_edg_stack_tr_lsun_640_d6_sig20_trname.t7" is only used to reference the filenames, as shown in https://github.com/zouchuhang/LayoutNet/blob/master/train_persp_joint_lsun_type.lua#L39-L47, you can build your only .t7 file by listing out all the filenames in the training set and store them in it.

**Comment by wanghxcis** [comment]
Thanks very much for your kindly answer.
